### ISSUE TITLE
Can't build the binary

### ISSUE THREAD

**Issue by zukko78** [pierrec/lz4#48]
go version go1.11.11 linux/amd64

/go/src/github.com/pierrec/lz4# go build .
# github.com/pierrec/lz4
./block.go:11:23: undefined: hashShift
./block.go:50:21: undefined: mfLimit
./block.go:72:31: undefined: winSize
./block.go:83:9: undefined: minMatch
./block.go:184:21: undefined: mfLimit
./block.go:192:29: undefined: winSize
./block.go:195:11: undefined: winSize
./block.go:207:74: undefined: winSize
./block.go:207:106: undefined: winMask
./block.go:225:12: undefined: minMatch
./block.go:225:12: too many errors

**Comment by zukko78** [comment]
with go version 1.10 is working as expected

**Comment by pierrec** [comment]
Should work with all versions from 1.9.
